# --- Constants ---
SPRITE_SCALING_PLAYER = 0.15
SPRITE_SCALING_COIN = 0.25
SPRITE_SCALING_LASER = 0.3
SPRITE_SCALING_EXPLOSION = 0.3
SPRITE_SCALING_BOSS = 0.6
SPRITE_SCALING_LASER_BOSS = 0.4
COIN_COUNT = 30

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "STARDUST"
MOVEMENT_SPEED = 5
BULLET_SPEED = 5
BOSS_BULLET_SPEED = 8